
GET http://localhost:5116/api/products

###
GET http://localhost:5116/api/products/2

###
POST http://localhost:5116/api/products/create
content-type: application/json

{
  "name": "New Product",
  "quantity": 100,
  "DateTime": "2025-03-24"
}
